# Generated by Django 6.1.1 on 2026-09-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='department',
        ),
    ]
