# Generated by Django 6.1.1 on 2026-09-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_department_id_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_created', models.CharField(default='No', max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=40)),
                ('days', models.IntegerField()),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RegularBillsRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
            ],
        ),
        migrations.AddField(
            model_name='createdrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.request'),
        ),
        migrations.CreateModel(
            name='ActualWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('total_steps', models.IntegerField()),
                ('request_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('approver_id', models.IntegerField()),
                ('approver_name', models.CharField(max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.request')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('total_steps', models.IntegerField()),
                ('request_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('approver_id', models.IntegerField()),
                ('approver_name', models.CharField(max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.request')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('total_steps', models.IntegerField()),
                ('request_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('approver_id', models.IntegerField()),
                ('approver_name', models.CharField(max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.createdrequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.request')),
            ],
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
