# Generated by Django 6.1.1 on 2026-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_createdrequest_request_leaverequestdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualworkflowstep',
            name='step_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actualworkflowstep',
            name='total_steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryworkflowstep',
            name='step_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryworkflowstep',
            name='total_steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='total_steps',
            field=models.IntegerField(null=True),
        ),
    ]
